<?php

namespace Database\Seeders;

use App\Models\Area;
use App\Models\Profesor;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProfesorSeeder extends Seeder
{
    /**
     * Docentes de la ESCOM (semestres 22-1, 22-2 y 23-1).
     * Origen: resources/docs/docentes.pdf
     */
    private const DOCENTES = [
        'Aguilar García Rafael',
        'Aguilar Sánchez Fernando',
        'Aguilar Velázquez Daniel',
        'Agustín Domínguez Verónica',
        'Albortante Morato Cecilia',
        'Alcántara Méndez Alberto Jesús',
        'Alcaraz Torres Juan Jesús',
        'Almazán Farfán Rocío',
        'Aragón García Maribel',
        'Araujo Díaz David',
        'Arzate Gordillo Jacqueline',
        'Ávila Sánchez Cristhian Alejandro',
        'Barrón Vera Josue Emanuel',
        'Bautista Rosales Sandra Ivette',
        'Blanco Almazan Ivan Eduardo',
        'Botello Castillo Alejandro',
        'Buitrón Damaso Israel',
        'Cabrera Chávez Gloría Lourdes',
        'Cancino Calderón Sergio',
        'Cancino Mosqueda Odette Berenice',
        'Cañedo Suárez Leticia',
        'Carbajal Hernández José Juan',
        'Carballo Jiménez Juan Manuel',
        'Carranza Castillo Oscar',
        'Carreto Arellano Chadwick',
        'Castillo Cabrera Gelacio',
        'Castillo Marrufo Juan Antonio',
        'Catalán Salgado Edgar Armando',
        'Ceballos Sebastián Ricardo',
        'Celis Domínguez Adriana Berenice',
        'Centeno Arrazola Maria Soledad',
        'Cervantes De Anda Ismael',
        'Cervantes Espinosa Luis Moctezuma',
        'Chavarría Báez Lorena',
        'Chávez Lima Eduardo',
        'Cifuentes Álvarez Alejandro Sigfrido',
        'Colin Hernández Nestor',
        'Cordero López Martha Rosa',
        'Corona Bermúdez Uriel',
        'Coronilla Contreras Ukranio',
        'Cortés Galicia Jorge',
        'Cortez Duarte Nidia Asunción',
        'Cruz García Daniel',
        'Cruz Lázaro Apolinar Francisco',
        'Cruz Meza María Elena',
        'Cruz Rojas Jorge Alberto',
        'Cruz Torres Benjamín',
        'Dávalos López José Carlos',
        'De la O Torres Saúl',
        'De Luna Caballero Roberto',
        'Díaz Huerta Claudia Celia',
        'Díaz Santiago Ricardo Felipe',
        'Díaz Santiago Sandra',
        'Díaz Toalá Iván',
        'Dorantes González Marco Antonio',
        'Dorantes Villa Claudia Jisela',
        'Durán Camarillo Edmundo René',
        'Durán Ledezma Ángel Adalberto',
        'Enríquez Zárate José Asunción',
        'Escamilla Miranda Patricia',
        'Esquivel Centeno José Armando',
        'Estrada Elizalde Serafín',
        'Fernández Vázquez Alfonso',
        'Ferrer Tenorio Jorge',
        'Figueroa Del Prado Felipe de Jesús',
        'Flores Delgado Raquel',
        'Flores Escobar José Antonio',
        'Flores Estrada Ituriel Enrique',
        'Flores Fuentes Naria Adriana',
        'Flores Mendoza Yaxkin',
        'Flores Meraz Yesica Sonia',
        'Franco Martínez Edgardo Adrián',
        'Galeana Chávez María del Rosario',
        'Galicia Mejía Rubén',
        'Galindo Durán Cristal Karina',
        'Galiñanes Rodríguez María Gabriela',
        'García Mendoza Consuelo Varinia',
        'García Ortega Victor Hugo',
        'García Sales Juan Vicente',
        'Gaspar Medina Fabián',
        'Gómez Tress Mariana',
        'González Albarrán Gisela',
        'González Cisneros Alejandro',
        'González García Gustavo',
        'González Ramírez Marko Alfonso',
        'González Trujillo Miguel Ángel',
        'Gutiérrez Aldana Eduardo',
        'Gutiérrez García Juan Jesús',
        'Gutiérrez Mejía Darwin',
        'Guzmán Aguilar Florencio',
        'Guzmán Flores Jessie Paulina',
        'Henestrosa Carrasco Leticia',
        'Hernández Aguilar José Luis',
        'Hernández Cruz Macario',
        'Hernández García Rosa Alba',
        'Hernández Jaime Josefína',
        'Hernández Olvera Luis Enrique',
        'Hernández Rubio Erika',
        'Hernández Secundino José Celestino Elías',
        'Hernández Vásquez César',
        'Herrera Yañez Crispin',
        'Jiménez Benítez José Alfredo',
        'Jiménez Contreras Edith Adriana',
        'Jiménez Galán Yasmín Ivette',
        'Jiménez Ruíz René Baltazar',
        'Jiménez Villanueva Martha Patricia',
        'Juárez Gambino Joel Omar',
        'Juárez León Carlos',
        'Juárez Martínez Genaro',
        'Juarez Mendez Ana Belem',
        'Juárez Ramírez Jazmín Adriana',
        'Jurado Jiménez Roberto',
        'Lazcano Xoxotla Laura',
        'Leal Pacheco Christian René',
        'León Hernández Miguel Abel',
        'Levario Medina Sergio',
        'Linares Vallejo Erick Eugenio',
        'López Rojas Ariel',
        'López Carrera Benjamín',
        'López Leyva Luis Octavio',
        'López Rodríguez Claudia Alejandra',
        'López Ruíz Gabriela de Jesús',
        'López Sánchez José Manuel',
        'Loyola Espinosa Araceli',
        'Luna Benoso Benjamín',
        'Macías Pérez Francisco Javier',
        'Maldonado Castillo Idalia',
        'Maldonado Muñoz Miguel Ángel',
        'Manzanilla Granados Héctor Manuel',
        'Márquez Arreguín Guillermo',
        'Martínez Acosta Lilian',
        'Martínez Díaz Juan Carlos',
        'Martínez García César Román',
        'Martínez Guerrero José Alfredo',
        'Martínez Nuño Jesús Alfredo',
        'Martínez Perales José Cruz',
        'Martínez Rosales Ricardo',
        'Mata Gil Patricia',
        'Medina Mejía Virginia',
        'Melara Abarca Reyna Elia',
        'Méndez Segundo Laura',
        'Mendoza Macías Elba',
        'Miguel Pilar Zelin',
        'Montes Meza Adbel Anahí',
        'Montiel Sánchez Ángel Salvador',
        'Morales Cruz Juan Carlos',
        'Morales González Ángel',
        'Morales Güitrón Sandra Luz',
        'Morales Rodríguez Úrsula Samantha',
        'Moreno Armendáriz Marco Antonio',
        'Moreno Cervantes Axel Ernesto',
        'Moreno Galván Elizabeth',
        'Moscoso Malagón Yosafat',
        'Mosso García Iván Giovanny',
        'Mújica Ascencio César',
        'Muñoz Salazar Laura',
        'Nava Lara Joel',
        'Ocampo Botello Fabiola',
        'Ocotitla Rojas Nancy',
        'Ojeda Guillén Didier',
        'Ortega González Rubén',
        'Ortigoza Campos Andrés',
        'Ortíz Ramírez José Antonio',
        'Ortuño Araujo Jesús',
        'Pachuca Herrera Yanira',
        'Palacios Solano Rocío',
        'Palma Orozco Rosaura',
        'Paredes Cadena Myriam Noemí',
        'Pastrana Fernández Carlos Jesús',
        'Peredo Valderrama Rubén',
        'Pérez de los Santos Mondragón Tanibet',
        'Pérez Pérez José Juan',
        'Pérez Vera Sandra Mercedes',
        'Pescador Rojas Miriam',
        'Pineda Guerrero Carlos',
        'Puebla Lomas Jaime Hugo',
        'Ramírez Martínez Elia Tzindejhé',
        'Ramírez Romero Tonáhtiu Arturo',
        'Ramírez Tenorio Rafael',
        'Rangel González Josué',
        'Reséndiz Muñoz Rocío',
        'Reyes Bermejo Tlatoani de Jesús',
        'Ríos de la Torre Ignacio',
        'Rivera De la Rosa Mónica',
        'Rocha Bernabé María del Rosario',
        'Rodríguez Castillo Miguel Ángel',
        'Rodríguez Flores Eduardo',
        'Rodríguez Jordán Gabriel de Jesús',
        'Rodríguez Ordaz Marisol',
        'Rodríguez Sarabia Tania',
        'Rodríguez Villarreal José Gregorio',
        'Rojas Mexicano Ismael',
        'Romero Herrera Rodolfo',
        'Rosas Trigueros Jorge Luís',
        'Rueda Meléndez José Marco Antonio',
        'Ruíz Ledesma Elena Fabiola',
        'Salas Ramirez Israel',
        'Salazar Ramírez Manuel',
        'Salinas Hernández Encarnación',
        'Salinas Lugo Sergio',
        'Sánchez Quintanilla Gilberto',
        'Sánchez Aguilar Alfonso',
        'Sánchez Arroyo José Emilio',
        'Sánchez Brito Miguel',
        'Sánchez Cruz Virginia',
        'Sánchez García Luz María',
        'Sánchez García Octavio',
        'Sánchez Juárez José',
        'Sánchez Mendoza Israel',
        'Sánchez Moreno Adriana de la Paz',
        'Sánchez Palacios María Susana',
        'Sánchez Vargas Perla Rebeca',
        'Santillán Luna Raúl',
        'Saucedo Delgado Rafael Norman',
        'Serrano Talamantes José Felix',
        'Silva García Victor Manuel',
        'Silva Martínez Jorge Javier',
        'Solorza Guzmán Misael',
        'Sosa Adán Fanny',
        'Soto Ramos Manuel Alejandro',
        'Suárez Castañón Miguel Santiago',
        'Tecla Parra Roberto',
        'Téllez Barrera Juan Carlos',
        'Téllez Reyes Ma. Socorro',
        'Tenorio Marrón Marco Antonio',
        'Testa Nava Alexis',
        'Tirado Lule Judith Margarita',
        'Torres González Enrique',
        'Vázquez Arreguín Roberto',
        'Vázquez González Leonor',
        'Vázquez Ortiz Mijaíl',
        'Vega García Nayeli',
        'Vélez Saldaña Ulises',
        'Vera Hernández Gumersindo',
        'Villegas Navarrete Sonia',
        'Viveros Vela Karina',
        'Winfield Reyes Ana María',
        'Zagal Flores Roberto Eswart',
        'Zárate Cárdenas Alejandro',
    ];

    public function run(): void
    {
        $area = Area::where('nombre', 'Docentes')->first();

        if (! $area) {
            $this->command->warn('Área Docentes no encontrada. Saltando ProfesorSeeder.');

            return;
        }

        foreach (self::DOCENTES as $nombre) {
            $email = Str::slug($nombre).'@bitets.mx';

            Profesor::firstOrCreate(
                ['email' => $email],
                [
                    'nombre' => $nombre,
                    'area_id' => $area->id,
                ],
            );
        }
    }
}
